### ISSUE TITLE
About option

### ISSUE THREAD

**Issue by Lmendev** [Lmendev/rollercoin-calculator#15]
Create a new `about` option in the main menu.

This will be a new page with information about the project.

Initially, the page should display: 

- Text showing that **rollercoin calculator** is an open source project 
- Link to github repository.

Improvements are welcome!

![image](https://user-images.githubusercontent.com/2933342/161965729-7add8adc-50cd-4ace-8877-7a99df628248.png)

**Comment by VitekDev** [comment]
#16

**Comment by VitekDev** [comment]
#16
