### ISSUE TITLE
Show github icon link 

### ISSUE THREAD

**Issue by Lmendev** [Lmendev/rollercoin-calculator#42]
Github image is not displayed in about section

**Comment by VitekDev** [comment]
it randomly adds ../ but there is nothing in the code
![image](https://github.com/Lmendev/rollercoin-calculator/assets/90604277/e08c16e1-e133-4577-9a9b-bd5c6aa548d5)

**Comment by Lmendev** [comment]
I think removing `../` from `src/pages/about.html` should be enough 🤔

```html
<img src="img/github.svg" alt="github logo" />
```

**Comment by Lmendev** [comment]
https://github.com/Lmendev/rollercoin-calculator/pull/46
